apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: private-repo-credentials
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: private-repo-https-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: "git"
        url: "https://github.com/misgav777/hw-k8s-config.git"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
  - secretKey: username
    remoteRef:
      key: argocd/repo-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: argocd/repo-credentials
      property: password